name: Deploy to GitHub Pages

on:
  push:
    branches:
      - issue-42-Move-website-files-to-root-of-project

permissions:
  contents: write

jobs:
  deploy:
    uses: ai-cfia/github-workflows/.github/workflows/workflow-gh-pages-deployment.yml@main
    with:
      node-version: 18
      publish-dir: ./build
      cache-dependency-path: .
      publish-branch: deployment
    secrets: inherit
